### ISSUE TITLE
阿里云短信的短信接口是不是变了？

### ISSUE THREAD

**Issue by royalwang** [phper2013/laravel-sms#1]
现在在阿里云上找不到短信接口了，现在的接口都是http(s)://{AccountId}.mns.cn-hangzhou.aliyuncs.com这种格式的了，找不到代码中的 https://sms.aliyuncs.com/ 这种接口文档了。
请问这个是接口变了，还是有其他的接口地址？

**Comment by phper2013** [comment]
https://help.aliyun.com/document_detail/44364.html?spm=5176.doc44363.6.572.zumCH6

**Comment by phper2013** [comment]
阿里云接口变了，本人帐号注册的早，所以一直是可以发送的，没注意，现在修复了。

https://help.aliyun.com/document_detail/55451.html
